# Generated by Django 5.1.3 on 2024-11-18 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_specialist', to='specialists.specialist'),
        ),
    ]
