# Generated by Django 5.1.3 on 2024-11-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
